### ISSUE TITLE
ErrorCode 10004 Invalid Sign (Market Order)

### ISSUE THREAD

**Issue by peepopoggers** [wassup-/bybit-rs#12]
When sending the below object into the module

```rs
PlaceActiveOrderData {
    symbol: "BTCUSDT",
    side: Buy,
    qty: 0.013,
    order_type: Market,
    price: None,
    time_in_force: PostOnly,
    close_on_trigger: None,
    order_link_id: None,
    take_profit: Some(
        47200.0,
    ),
    stop_loss: Some(
        46150.0,
    ),
    tp_trigger_by: None,
    sl_trigger_by: None,
    reduce_only: None,
}
```
Using this code:
```rs
let order_result = api.place_active_order(order_data).await?;
```
I recieve this error:
`
!! Function Exited: ErrorCode { code: 10004, msg: "error sign! origin_string[api_key=[API KEY]&close_on_trigger=&order_link_id=&order_type=Market&price=&qty=0.013&reduce_only=&side=Buy&sl_trigger_by=&stop_loss=46150.0&symbol=BTCUSDT&take_profit=47200.0&time_in_force=PostOnly&timestamp=1641231577879&tp_trigger_by=]", ext_code: "", ext_info: "" } !!`

**Comment by wassup-** [comment]
I will take a look at why this is happening. My gut is telling me this has something to do with optional parameters.

**Comment by peepopoggers** [comment]
I added the stop_loss and take_profit optional parameters and the rest are mandatory / default

**Comment by peepopoggers** [comment]
Hi, if you do not have time let me know, I will debug this myself if you cannot just lmk :>

**Comment by peepopoggers** [comment]
Ok so looking at the API docs, the optional params are not shown as to be passed:
```
curl https://api-testnet.bybit.com/v2/private/order/create \
-H "Content-Type: application/json" \
-d '{"api_key":"{api_key}","side":"Buy","symbol":"BTCUSD","order_type":"Market","qty":10,"time_in_force":"GoodTillCancel","timestamp":{timestamp},"sign":"{sign}"}'
```
so empty parameters do not need to be passed, which as you say probably is the issue. an if(!None) or something would help with this ;>

**Comment by wassup-** [comment]
I had the the chance to take a look at this yesterday evening, but was unable to get to a solution yet.

Bybit expect us to sign authenticated requests by creating a query string from all request parameters, calculate a hash from this query string and our secret, and include this hash in the request to the API. However, there is a difference between how bybit and `serde_urlencoded` handle optional parameters.

Basically, bybit will include optional parameters in the generated query string, but `serde_urlencoded` just excludes them from the query string altogether.

Assuming we have the following query:
```rs
struct Query {
    a: i32,         // = 1
    b: Option<i32>, // = None
    c: i32          // = 3
}
```
bybit will generate the following query string: `a=1&b=&c=3`
but we generate the following query string: `a=1&c=3`

Since the author of `serde_urlencoded` is [not planning on supporting this use case](https://github.com/nox/serde_urlencoded/issues/36#issuecomment-450348356), I see a couple of options to tackle this issue:
1) We write our own UrlEncodedSerializer which serializes `None` as an empty string, and is used solely by our http signer.
2) We create separate structs specifically for signing purposes, and use those instead of the query itself.
3) We decorate each `Option` with the [following code](https://github.com/ruma/ruma/blob/56801780b659be609bbcb9ce3701ed2676130304/crates/ruma-serde/src/strings.rs#L39), which saves us from having to create separate structs altogether.

(3) would be the easiest way out, however I'm afraid this will do more harm than good, because that would for example serialize a `None` `Option<i32>` to JSON as `""` (an empty string), which is definitely not what we want.

Which leaves us with both (1) and (2).  

To me (1) sounds like the cleanest solution. However this probably involves writing quite a lot of boilerplate code, basically replacing `serde_urlencoded` with our own custom solution.
The more I think about it, a combination of (2) and (3) may in fact be the way to go. Sure we (and users of this library) will have to basically duplicate entire structs, and decorate one of them with the code from (3), but this will save us from having to implement a custom serializer altogether.

What do you think? Maybe I'm missing something?

**Comment by wassup-** [comment]
> Ok so looking at the API docs, the empty params are shown as to be not passed (for example stop_loss is not passed):
> 
> ```
> curl https://api-testnet.bybit.com/v2/private/order/create \
> -H "Content-Type: application/json" \
> -d '{"api_key":"{api_key}","side":"Buy","symbol":"BTCUSD","order_type":"Market","qty":10,"time_in_force":"GoodTillCancel","timestamp":{timestamp},"sign":"{sign}"}'
> ```
> 
> so empty parameters do not need to be passed, which as you say probably is the issue. an if(!None) or something would help with this ;>

Sorry I did not see your response when I was writing mine.
You may in fact be right about this! To test this, we can easily exclude `None` optionals from the request by using the following code for all `Option`s
```rs
#[serde(skip_serializing_if = "Option::is_none")]
pub stop_loss: Option<f64>,
```

Could you try this out and let me know if this works?

**Comment by peepopoggers** [comment]
Will do :+1:

**Comment by peepopoggers** [comment]
First, could you accept my pr? :>

**Comment by wassup-** [comment]
Done

**Comment by peepopoggers** [comment]
Okay so in rest/orders.rs I changed PlaceActiveOrderData to this:
```rs
#[derive(Debug, Default, Serialize)]
pub struct PlaceActiveOrderData {
    pub symbol: String,
    pub side: Side,
    pub qty: f64,
    pub order_type: OrderType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<f64>,
    pub time_in_force: TimeInForce,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub close_on_trigger: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order_link_id: Option<OrderLinkId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub take_profit: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stop_loss: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tp_trigger_by: Option<TriggerPrice>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sl_trigger_by: Option<TriggerPrice>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reduce_only: Option<bool>,
}
```
But it still passed empty variables into the URL. Am I missing something?

**Comment by wassup-** [comment]
If we take a look at [src/rest/orders.rs#L123](https://github.com/wassup-/bybit-rs/blob/2d2e826ff922457ec0f7676d817f6a13fa81a783/src/rest/orders.rs#L123), we can see that `PlaceActiveOrder` is not the payload sent to the API, however `request::CreateOrder` is. So we should change that one instead.

**Comment by peepopoggers** [comment]
Alright so where is request::ListActiveOrders? Confused on what to change

**Comment by wassup-** [comment]
> Alright so where is request::ListActiveOrders? Confused on what to change

request::ListActiveOrders is at [src/rest/orders.rs#L203](https://github.com/wassup-/bybit-rs/blob/2d2e826ff922457ec0f7676d817f6a13fa81a783/src/rest/orders.rs#L203), but we should be changing request::CreateOrder instead

**Comment by peepopoggers** [comment]
oh woops i mean wheres `request::CreateOrder`

**Comment by peepopoggers** [comment]
Hi, I fixed error 10004 but there is another error now (10001) about qty field. Here is what it is:
```rs
ErrorCode { code: 10001, msg: "Param validation for 'qty' failed on the 'required' tag", ext_code: "", ext_info: "" }
```
