### ISSUE TITLE
ErrorCode 10001 (Market Order)

### ISSUE THREAD

**Issue by peepopoggers** [wassup-/bybit-rs#15]
When using the following parameters for an order:
```rs
PlaceActiveOrderData {
    symbol: "BTCUSDT",
    side: Buy,
    qty: 0.013,
    order_type: Market,
    price: None,
    time_in_force: PostOnly,
    close_on_trigger: None,
    order_link_id: None,
    take_profit: Some(
        50000.0,
    ),
    stop_loss: Some(
        41000.0,
    ),
    tp_trigger_by: None,
    sl_trigger_by: None,
    reduce_only: None,
}
```
I get:
```rs
ErrorCode { code: 10001, msg: "Param validation for 'qty' failed on the 'required' tag", ext_code: "", ext_info: "" }
```

Also,
When I pass the following I get the same error code but a different message:

```rs
PlaceActiveOrderData {
    symbol: "BTCUSDT",
    side: Buy,
    qty: 0.004583041053733335,
    order_type: Market,
    price: None,
    time_in_force: PostOnly,
    close_on_trigger: None,
    order_link_id: None,
    take_profit: Some(
        50000.0,
    ),
    stop_loss: Some(
        41000.0,
    ),
    tp_trigger_by: None,
    sl_trigger_by: None,
    reduce_only: None,
}
```
I get:
```rs
ErrorCode { code: 10001, msg: "Param validation for 'symbol' failed on the 'symbol' tag", ext_code: "", ext_info: "" }
```

Very strange reaction as the error is different even though the qty is only different by a little bit. Any ideas what these are? :P

**Comment by peepopoggers** [comment]
I think the second is due to the linear pair not being supported so I think that is not an issue, but I would like linear pairs implemented soon, so I will contribute to at least add orders.

For first still confused.

**Comment by wassup-** [comment]
I'm not sure if this is related, but according to the Bybit docs
> Quantity (qty) ... Must conform to the symbol's qty_step. 

In the case of **BTCUSDT**, `qty_step = 0.001` so I'd actually expect `0.013` to pass, and `0.004583041053733335` to fail validation. I'm guessing the error they are returning is incorrect, which may be related to the fact that we are using the wrong endpoint to create **BTCUSDT** orders. This feeling is enforced since in the second example they are returning a whole different validation error, which isn't even related to the `qty` field at all, even though that is the only one that has changed between those two requests.

We should re-test this once #18 has been finished.

**Comment by peepopoggers** [comment]
This code helped fix:

```rs
let q_symbols = api.fetch_symbols().await?;
let symbol_info = q_symbols.symbols().into_iter().find(|symbol| symbol.alias == *pair).unwrap();
let min_qty = symbol_info.lot_size_filter.min_trading_qty;
let qty_step = symbol_info.lot_size_filter.qty_step;

//change quantity to buy to stepped version so bybit api can accept it
qty_to_buy = (qty_to_buy/qty_step).round() * qty_step;
```
